Use apt-get install to install adb and fastboot

diff --git a/scripts/install_sdk b/scripts/install_sdk
--- a/scripts/install_sdk
+++ b/scripts/install_sdk
@@ -2,7 +2,7 @@
 . scripts/functions    
 clear
 
-F_PleaseWait
+echo -e "\n Installing SDK... \n$(F_PleaseWait)"
 
 curl -s http://developer.android.com/sdk/index.html > sdk.html
 SDK_LINK=$(grep -i linux-tools sdk.html | awk -F'"' '{print $6}')
@@ -12,6 +12,7 @@ rm sdk.html
 F_Download $SDK_ZIPNAME $SDK_LINK SDK
 
 # Extract SDK
+SDK_Error=0
 SDK_Install=0
 
 if [ ! -d "android-sdk-linux" ]; then
@@ -21,6 +22,7 @@ if [ ! -d "android-sdk-linux" ]; then
 	
 	if [ $? -eq 0 ]; then
 		echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"
+		sudo chmod -R 777 android-sdk-linux
 	else
 		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
 		echo -e " ${COLOR_Red}Error when extracting SDK.${COLOR_Wipe}\n"
@@ -28,8 +30,6 @@ if [ ! -d "android-sdk-linux" ]; then
 		exit
 	fi
 fi
-
-sudo chmod -R 777 android-sdk-linux
 
 # Download SDK-Tools
 
@@ -57,8 +57,7 @@ if [ ! -d android-sdk-linux/build-tools ]; then
 	else
 		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
 		echo -e " ${COLOR_Red}Error when extracting SDK build-tools.${COLOR_Wipe}\n"
-		F_PressEnter
-		exit
+		SDK_Error=1
 	fi
 fi
 
@@ -74,51 +73,32 @@ F_Download $SDKPTOOLS_ZIPNAME $SDKPTOOLS_LINK platform-tools
 
 # Extract SDK Platform Tools
 
-SDK_Platformtool=0
+PLATFORM_TOOLS="android-tools-adb android-tools-fastboot"
 
-if [ ! -d android-sdk-linux/platform-tools ]; then
-	SDK_Install=1
-	echo -n -e "\n Extracting SDK platform-tools... "
-	unzip -qq -o $SDKPTOOLS_ZIPNAME -d android-sdk-linux/
-	
-	if [ $? -eq 0 ]; then
-		sudo chmod -R 777 android-sdk-linux/platform-tools
-		echo -e "${COLOR_Green}SUCCESS${COLOR_Wipe}"
-	else
-		SDK_Platformtool=1
-		echo -e "${COLOR_Red}ERROR${COLOR_Wipe}\n"
-		echo -e " ${COLOR_Red}Error when extracting SDK platform-tools.${COLOR_Wipe}\n"
-		F_PressEnter
-		exit
+for package in $PLATFORM_TOOLS
+do
+	if ! dpkg -s "$package" 2>/dev/null | grep -q -i "install ok installed"; then
+		SDK_Install=1
+
+		echo -n -e "\n Installing $package... "
+		sudo apt-get -y install $package 2>/dev/null 1>/dev/null
+		
+		if ! dpkg -s "$package" 2>/dev/null | grep -q -i "install ok installed"; then
+			echo -e -n "${COLOR_Red}ERROR${COLOR_Wipe}"
+			SDK_Error=1
+		else
+			echo -e -n "${COLOR_Green}SUCCESS${COLOR_Wipe}"
+		fi
+
 	fi
-fi
+done
 
-if [ $SDK_Platformtool == 0 ]; then
-	if ! grep -q -i "export PATH=" ~/.bashrc; then
-		echo >> ~/.bashrc
-		echo "export PATH=$(pwd)/android-sdk-linux/tools:$PATH" >> ~/.bashrc
-	elif ! grep -q -i "=$(pwd)/android-sdk-linux/tools" ~/.bashrc && ! grep -q -i "$(pwd)/android-sdk-linux/tools:" ~/.bashrc  && ! grep -q -i ":$(pwd)/android-sdk-linux/tools" ~/.bashrc; then
-		var=$(grep -i "export PATH=" ~/.bashrc)
-		sed -i '/export PATH=/d' ~/.bashrc
-		echo $var":$(pwd)/android-sdk-linux/tools" >> ~/.bashrc
-	fi
-	 
-	if ! grep -q -i "export PATH=" ~/.bashrc; then
-		echo >> ~/.bashrc
-		echo "export PATH=$(pwd)/android-sdk-linux/platform-tools:$PATH" >> ~/.bashrc
-	elif ! grep -q -i "=$(pwd)/android-sdk-linux/platform-tools" ~/.bashrc && ! grep -q -i "$(pwd)/android-sdk-linux/platform-tools:" ~/.bashrc  && ! grep -q -i ":$(pwd)/android-sdk-linux/platform-tools" ~/.bashrc; then
-		var=$(grep -i "export PATH=" ~/.bashrc)
-		sed -i '/export PATH=/d' ~/.bashrc
-		echo $var":$(pwd)/android-sdk-linux/platform-tools" >> ~/.bashrc
-	fi
-fi
-
-source ~/.bashrc
-
-if [ $SDK_Install == 1 ]; then
-	echo -e "\n ${COLOR_Green}The installation of SDK was successful.${COLOR_Wipe}"
+if [ $SDK_Install == 1 ] && [ $SDK_Error == 0 ]; then
+	echo -e "\n\n The installation of the SDK was successful."
+elif [ $SDK_Install == 1 ] && [ $SDK_Error == 1 ]; then
+	echo -e "\n\n There were one or more errors during the installation of the SDK."
 else
-	echo -e "\n ${COLOR_Yellow}SDK is already installed.${COLOR_Wipe}"
+	echo -e "${COLOR_Yellow} ALREADY INSTALLED${COLOR_Wipe}"
 fi
 echo
 
